- src/main/java/be15fintomatokatchupbe/auth/command/controller/AuthCommandController.java
- src/main/java/be15fintomatokatchupbe/auth/command/service/AuthCommandService.java
- src/main/java/be15fintomatokatchupbe/user/command/application/controller/UserCommandController.java
- src/main/java/be15fintomatokatchupbe/user/command/application/dto/request/ChangePasswordRequest.java
- src/main/java/be15fintomatokatchupbe/user/command/application/repository/UserRepository.java
- src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
- src/main/java/be15fintomatokatchupbe/user/exception/UserErrorCode.java
> Feat: 비밀번호 변경 구현

- src/main/java/be15fintomatokatchupbe/user/command/application/dto/request/SignupRequest.java
- src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/User.java
> Tmt 58 be 인플루언서 관리 등록

- src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateChanceRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/response/Exam.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Campaign.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/repository/PipelineRepository.java
- src/main/java/be15fintomatokatchupbe/campaign/exception/CampaignErrorCode.java
- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/Exam.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/Exam.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
> chore: 캠페인 폴더 구조 생성

- src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/controller/InfluencerCommandController.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/dto/request/InfluencerRegisterRequestDTO.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/dto/response/InfluencerRegisterResponse.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/service/InfluencerCommandService.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/service/InfluencerCommandServiceImpl.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Influencer.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Instagram.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Youtube.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/CategoryRepository.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/HashtagInfluencerCampaignRepository.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/InfluencerRepository.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/InstagramRepository.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/YoutubeRepository.java
{
"success": true,
"data": {
"influencerId": 20,
"name": "김인직",
"youtubeConnected": false,
"instagramConnected": false,
"categoryNames": [
"Entertainment",
"Food",
"Gaming"
]
},
"errorCode": null,
"message": null,
"timestamp": "2025-06-19T16:08:28.2130184"
}
> Tmt 66 인플루언서 관리 등록

- src/main/java/be15fintomatokatchupbe/common/domain/GenderType.java
- src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/PicFile.java
- src/main/java/be15fintomatokatchupbe/user/query/controller/Exam.java
- src/main/java/be15fintomatokatchupbe/user/query/controller/UserQueryController.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/Exam.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserAccountQueryResponse.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserInfluencerListDTO.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserInfluencerListResponse.java
- src/main/java/be15fintomatokatchupbe/user/query/mapper/Exam.java
- src/main/java/be15fintomatokatchupbe/user/query/mapper/UserQueryMapper.java
- src/main/java/be15fintomatokatchupbe/user/query/service/Exam.java
- src/main/java/be15fintomatokatchupbe/user/query/service/UserQueryService.java
- src/main/resources/mappers/user/UserQueryMapper.xml
- 내 계정 정보 조회 구현
- 내 인플루언서 목록 조회 구현
포스트맨  정상 작동
> Tmt 64 be 내 개인정보 조회 구현

- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/MainDashboardQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ClientCompanyResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/SalesActivityResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/MainDashboardQueryMapper.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/MainDashboardQueryService.java
- src/main/resources/mappers/dashboard/MainDashboardQueryMapper.xml
> Tmt 71 be 고객사 조회 기능

- src/main/java/be15fintomatokatchupbe/relation/service/PipeUserService.java
- src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
- src/main/java/be15fintomatokatchupbe/user/command/application/support/UserHelperService.java
> fix: 헬퍼 폴더 구조 변경

- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/MainDashboardQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ContractResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/MainDashboardQueryMapper.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/MainDashboardQueryService.java
- src/main/resources/mappers/dashboard/MainDashboardQueryMapper.xml
> Tmt 80 be 메인 대시보드 계약 조회 기능

- src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/BasePipelineRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateChanceRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateProposalRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/IdeaRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/InfluencerProposalRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/InfluencerRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/InfluencerRevenueRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/support/CampaignHelperService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/constant/PipelineStatusConstants.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/constant/PipelineStepConstants.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Campaign.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/CampaignStatus.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/File.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Idea.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/PipelineStatus.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/PipelineStep.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/repository/CampaignRepository.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/repository/IdeaRepository.java
- src/main/java/be15fintomatokatchupbe/campaign/exception/CampaignErrorCode.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/support/InfluencerHelperService.java
- src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/InfluencerRepository.java
- src/main/java/be15fintomatokatchupbe/relation/service/PipeInfClientManagerService.java
- src/test/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandServiceTest.java
> Tmt 78 be 제안 생성 페이지

- build.gradle
- src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatCommandController.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/dto/request/CreateChatRoomRequest.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/dto/response/CreateChatRoomResponse.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/service/ChatCommandService.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/aggregate/entity/Chat.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/aggregate/entity/UserChat.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/ChatRoomRepository.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/UserChatRepository.java
- src/main/java/be15fintomatokatchupbe/chat/exception/ChatErrorCode.java
- src/main/resources/application.yml
- src/test/java/be15fintomatokatchupbe/chat/command/application/service/ChatCommandServiceTest.java
> Tmt 84 채팅방 생성

- src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatCommandController.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/dto/request/ExitChatRoomRequest.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/dto/response/ExitChatRoomResponse.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/service/ChatCommandService.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/UserChatRepository.java
- src/main/java/be15fintomatokatchupbe/chat/exception/ChatErrorCode.java
- src/test/java/be15fintomatokatchupbe/chat/command/application/service/ChatCommandServiceTest.java
> feat: 채팅 나가기 기능 구현

- src/main/java/be15fintomatokatchupbe/client/command/application/controller/ClientCompanyCommandController.java
- src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientCompanyRequest.java
- src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientManagerRequest.java
- src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandService.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientCompany.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientCompanyStatus.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientManagerStatus.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/constant/ClientCompanyStatusConstants.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/constant/ClientManagerStatusConstants.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/repository/ClientCompanyStatusRepository.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/repository/ClientManagerStatusRepository.java
- src/main/java/be15fintomatokatchupbe/client/command/exception/ClientErrorCode.java
- src/main/java/be15fintomatokatchupbe/common/exception/GlobalExceptionHandler.java
- src/main/java/be15fintomatokatchupbe/common/validation/ValidEmail.java
- src/main/java/be15fintomatokatchupbe/common/validation/ValidPhoneNumber.java
- src/main/java/be15fintomatokatchupbe/common/validation/validator/EmailValidator.java
- src/main/java/be15fintomatokatchupbe/common/validation/validator/PhoneNumberValidator.java
- src/test/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandServiceTest.java
- 고객사 등록 기능 구현
- 사원 등록 기능 구현
- soft delete로 적용
- 이메일, 전화번호 커스텀 데코레이터 적용
- 이메일 형식이 아닐 때 에러코드 보내주기
- 전화번호 형식이 아닐 때 에러코드 보내주기
> Tmt 77 be 고객사 및 사원 등록 기능 구현

- .github/workflows/pr-test.yml
- build.gradle
- src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
- src/main/java/be15fintomatokatchupbe/config/WebClientConfig.java
- src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeOAuthQueryController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/YoutubeStatsResponse.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeAnalyticsService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
- src/main/resources/application.yml
- src/test/java/be15fintomatokatchupbe/oauth/query/service/YoutubeAnalyticsServiceTest.java
- src/test/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryServiceTest.java
[테스트 방법]
1.[api요청링크]( http://localhost:8080/api/v1/oauth2/authorize/youtube) ← 접속 후 엑세스 토큰, 채널ID 받아냄
2. 포스트맨에 저장된 요청에 엑세스 토큰, 채널ID 넣어서 테스트 하면 됨
3. 일단 뒷일은 오늘 차차 할게요 ㅎ
> Tmt 93 be 유튜브 analytics api 연동

- build.gradle
- src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatSocketController.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/aggregate/entity/Message.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageRepository.java
- src/main/java/be15fintomatokatchupbe/config/JwtHandshakeInterceptor.java
- src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
- src/main/java/be15fintomatokatchupbe/config/StompAuthChannelInterceptor.java
- src/main/java/be15fintomatokatchupbe/config/WebSocketConfig.java
- src/main/java/be15fintomatokatchupbe/config/security/JwtAuthenticationFilter.java
- src/main/java/be15fintomatokatchupbe/utils/jwt/JwtTokenProvider.java
- src/main/resources/static/test.html
> feat/ 채팅 전송 구현 완료

- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/ProposalSearchRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/Exam.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ProposalCardResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ProposalSearchResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/application.yml
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
- src/test/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryServiceTest.java
> Tmt 89 be 제안 목록 조회

- src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateQuotationRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Campaign.java
- src/main/java/be15fintomatokatchupbe/relation/service/PipeInfClientManagerService.java
- src/test/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandServiceTest.java
요청 : 
```
{
"campaignId": 1,
"pipelineStatusId": 2,
"clientCompanyId": 1,
"clientManagerId": 3,
"userId": [1, 2],
"name": "2025년 여름 캠페인 견적",
"requestAt": "2025-06-23T10:00:00",
"startedAt": "2025-06-25T00:00:00",
"endedAt": "2025-07-01T00:00:00",
"presentedAt": "2025-06-24T15:00:00",
"campaignName": "여름 캠페인",
"content": "제품 소개 및 리뷰 제안",
"ideaList": [
{ "content": "이벤트 콘텐츠 제작" },
{ "content": "비하인드 영상 공개" }
],
"influencerId": [
{ "influencerId": 10 },
{ "influencerId": 11 }
],
"expectedRevenue": 175000,
"availableQuantity": 50,
"expectedProfit": 400000
}
```
결과 :
포스트맨 저장햇시유
> Tmt 102 be 견적 등록

- src/main/java/be15fintomatokatchupbe/contract/query/application/service/domain/aggregate/DigitalContract.java
- src/main/java/be15fintomatokatchupbe/contract/query/controller/DigitalContractQueryController.java
- src/main/java/be15fintomatokatchupbe/contract/query/dto/request/DigitalContractDetailRequest.java
- src/main/java/be15fintomatokatchupbe/contract/query/dto/response/DigitalContractDTO.java
- src/main/java/be15fintomatokatchupbe/contract/query/dto/response/DigitalContractDetailResponse.java
- src/main/java/be15fintomatokatchupbe/contract/query/dto/response/DigitalContractListResponse.java
- src/main/java/be15fintomatokatchupbe/contract/query/mapper/DigitalContractMapper.java
- src/main/java/be15fintomatokatchupbe/contract/query/service/DigitalContractQueryService.java
- src/main/resources/mappers/contract/DigitalContractQueryMapper.xml
- src/test/java/be15fintomatokatchupbe/contract/query/application/service/DigitalContractQueryServiceTest.java
{
"success": true,
"data": {
"detail": [
{
"digitalContractId": 1,
"template": "디폴트 계약서 템플릿입니다."
},
{
"digitalContractId": 2,
"template": "테스트용 계약서 입니다."
}
]
},
"errorCode": null,
"message": null,
"responseTime": "2025-06-23T17:17:18.9487994"
}
{
"success": true,
"data": {
"digitalContractId": 1,
"template": "디폴트 계약서 템플릿입니다.",
"createdAt": "2025-06-23T06:25:15",
"content": "디폴트",
"used": true
},
"errorCode": null,
"message": null,
"responseTime": "2025-06-23T17:17:34.2994995"
}
> feat/ 전자계약서 목록 조회 , 내용 조회

- src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientCompanyRequest.java
- src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/UpdateClientCompanyRequest.java
- src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandService.java
- src/main/java/be15fintomatokatchupbe/relation/domain/ClientCompanyUser.java
- src/main/java/be15fintomatokatchupbe/relation/repository/ClientCompanyUser.java
- src/main/java/be15fintomatokatchupbe/relation/repository/ClientCompanyUserRepository.java
- src/main/java/be15fintomatokatchupbe/relation/service/ClientCompanyUserService.java
- src/test/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandServiceTest.java
> Tmt 105 be 고객사 등록 수정 시 담당자 필드 추가

- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignSatisfactionDTO.java
- src/main/java/be15fintomatokatchupbe/email/command/application/controller/EmailCommandController.java
- src/main/java/be15fintomatokatchupbe/email/command/application/dto/request/exam.java
- src/main/java/be15fintomatokatchupbe/email/command/application/dto/response/Exam.java
- src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
- src/main/java/be15fintomatokatchupbe/email/exception/EmailErrorCode.java
- src/main/java/be15fintomatokatchupbe/email/query/controller/EmailQueryController.java
- src/main/java/be15fintomatokatchupbe/email/query/dto/request/EmailSearchRequest.java
- src/main/java/be15fintomatokatchupbe/email/query/dto/response/CampaignSatisfactionDTO.java
- src/main/java/be15fintomatokatchupbe/email/query/dto/response/CampaignSatisfactionResponse.java
- src/main/java/be15fintomatokatchupbe/email/query/mapper/EmailQueryMapper.java
- src/main/java/be15fintomatokatchupbe/email/query/service/EmailQueryService.java
- src/main/resources/mappers/email/EmailQueryMapper.xml
- src/test/java/be15fintomatokatchupbe/email/query/service/EmailQueryServiceTest.java
- 만족도 조사 목록 조회 구현
유튜브 링크가 있으면 그 해당 영상의 썸네일도 갖고올수있게
인스타는 x
> Tmt 82 be 만족도 조사 목록 조회 구현

- src/main/java/be15fintomatokatchupbe/contract/command/application/controller/DigitalContractCommandController.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/DigitalContractCreateRequest.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/dto/response/DigitalContractCreateResponse.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/DigitalContractCommandService.java
- src/test/java/be15fintomatokatchupbe/contract/command/application/service/DigitalContractCommandServiceTest.java
> feat/ 전자계약서  템플릿 생성 기능 구현

- .github/workflows/pr-test.yml
- build.gradle
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
- src/main/java/be15fintomatokatchupbe/config/AwsConfig.java
- src/main/java/be15fintomatokatchupbe/file/controller/FileController.java
- src/main/java/be15fintomatokatchupbe/file/domain/File.java
- src/main/java/be15fintomatokatchupbe/file/dto/FileDownloadResult.java
- src/main/java/be15fintomatokatchupbe/file/exception/FileErrorCode.java
- src/main/java/be15fintomatokatchupbe/file/repository/FileRepository.java
- src/main/java/be15fintomatokatchupbe/file/service/FileService.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/dto/FileDTO.java
- src/main/java/be15fintomatokatchupbe/utils/FileUtil.java
- src/main/resources/application.yml
> feat: 파일 업로드, 저장 구현

- src/main/java/be15fintomatokatchupbe/calendar/command/application/controller/CalendarCommandController.java
- src/main/java/be15fintomatokatchupbe/calendar/command/application/service/CalendarCommandService.java
- src/main/java/be15fintomatokatchupbe/calendar/exception/CalendarErrorCode.java
캘린더 일정 삭제 기능 구현
& CalendarErrorCode 파일 이름 변경
> 캘린더 일정 삭제 기능 구현

- src/main/java/be15fintomatokatchupbe/client/command/application/controller/ClientManagerCommandController.java
- src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandService.java
- src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientManagerCommandService.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientManager.java
- src/main/java/be15fintomatokatchupbe/client/command/domain/repository/ClientManagerRepository.java
- src/main/java/be15fintomatokatchupbe/client/command/exception/ClientErrorCode.java
> Tmt 117 사원 삭제 기능 구현

- src/main/java/be15fintomatokatchupbe/email/command/application/controller/EmailCommandController.java
- src/main/java/be15fintomatokatchupbe/email/command/application/dto/request/EmailSendSatisfactionRequest.java
- src/main/java/be15fintomatokatchupbe/email/command/application/dto/request/exam.java
- src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
- src/main/java/be15fintomatokatchupbe/email/command/domain/aggregate/Satisfaction.java
- src/main/java/be15fintomatokatchupbe/email/command/domain/repository/SatisfactionRepository.java
- src/main/java/be15fintomatokatchupbe/email/exception/EmailErrorCode.java
> Feat: 만족도 조사 평가 요청 구현

- src/main/java/be15fintomatokatchupbe/campaign/query/dto/ProposalCardDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
- src/test/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryServiceTest.java
> fix: 조회 응답 양식 수정, 쿼리 템플릿화

- src/main/java/be15fintomatokatchupbe/client/query/controller/ClientCompanyQueryController.java
- src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyDetailResponse.java
- src/main/java/be15fintomatokatchupbe/client/query/dto/ClientManagerDTO.java
- src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientCompanyQueryMapper.java
- src/main/java/be15fintomatokatchupbe/client/query/service/ClientCompanyQueryService.java
- src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
> Tmt 118 be 고객사 및 사원 상세 조회 기능 구현

- src/main/java/be15fintomatokatchupbe/client/query/controller/ClientManagerQueryController.java
- src/main/java/be15fintomatokatchupbe/client/query/dto/ClientManagerSimpleResponse.java
- src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientCompanyQueryMapper.java
- src/main/java/be15fintomatokatchupbe/client/query/service/ClientManagerQueryService.java
- src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
> Tmt 121 be 고객사 사원 목록 조회 기능 구현

- .gitignore
- build.gradle
- src/main/java/be15fintomatokatchupbe/config/GoogleSheetConfig.java
- src/main/java/be15fintomatokatchupbe/email/command/application/controller/EmailCommandController.java
- src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
- src/main/java/be15fintomatokatchupbe/email/command/domain/aggregate/Satisfaction.java
- src/main/java/be15fintomatokatchupbe/email/exception/EmailErrorCode.java
- src/main/resources/application.yml
- 화면에서 요청을 누르면 총점이 뜨게 구현
- 각 항목에 대한 점수들은 조회에서 할 예정
> Feat: 만족도 평가 결과 요청 구현

- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/ContractCardDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/RevenueCardDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ContractCardResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ContractSearchResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/RevenueCardResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/RevenueSearchResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> Tmt 135 be 계약 목록 조회

- src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientManagerQueryMapper.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/controller/ContractCommandController.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/ContractObjectUpdateRequest.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/DetailCreateRequest.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/DetailUpdateRequest.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/ContractObjectCommandService.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
- src/main/java/be15fintomatokatchupbe/contract/command/domain/entity/ContractObject.java
- src/main/java/be15fintomatokatchupbe/contract/command/domain/repository/ContractFileRepository.java
- src/main/java/be15fintomatokatchupbe/contract/command/domain/repository/DetailRepository.java
- src/main/java/be15fintomatokatchupbe/contract/command/domain/repository/ObjectRepository.java
- src/main/java/be15fintomatokatchupbe/contract/exception/DigitalContractErrorCode.java
- src/main/java/be15fintomatokatchupbe/contract/query/controller/ContractQueryController.java
- src/main/java/be15fintomatokatchupbe/contract/query/controller/SendEmailController.java
- src/main/java/be15fintomatokatchupbe/contract/query/dto/request/ClientManagerSearchRequest.java
- src/main/java/be15fintomatokatchupbe/contract/query/dto/response/ClientManagerResponse.java
- src/main/java/be15fintomatokatchupbe/contract/query/service/SendEmailService.java
- src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
- src/main/resources/mappers/client/ClientManagerQueryMapper.xml
- src/main/resources/mappers/contract/DetailMapper.xml
> feat/ 계약서 양식 CRUD 기능 구현 , 메일 리스트 조회

- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Idea.java
- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/ContractFormDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ContractDetailResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ContractFormResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/FileInfo.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/common/PipelineFormResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> feat: 계약 상세정보 조회 개발

- src/main/java/be15fintomatokatchupbe/contract/command/application/controller/ContractCommandController.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/SendEmailRequest.java
- src/main/java/be15fintomatokatchupbe/utils/EmailUtils.java
> Tmt 143 be 메일 전송

- src/main/java/be15fintomatokatchupbe/contract/command/application/controller/ContractSuccessCommandController.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/ContractObjectCommandService.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/ContractSuccessCommandService.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
- src/main/java/be15fintomatokatchupbe/contract/command/domain/entity/Contract.java
- src/main/java/be15fintomatokatchupbe/contract/command/domain/entity/ContractFile.java
- src/main/java/be15fintomatokatchupbe/contract/command/domain/repository/ContractRepository.java
- src/main/java/be15fintomatokatchupbe/contract/exception/ContractErrorCode.java
- src/main/java/be15fintomatokatchupbe/file/service/FileService.java
> Tmt 147 be 계약서 파일 등록 구현

- src/main/java/be15fintomatokatchupbe/campaign/exception/CampaignErrorCode.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/CampaignDashboardQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignContentResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/CampaignDashboardQueryMapper.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
- src/main/java/be15fintomatokatchupbe/email/exception/EmailErrorCode.java
- src/main/java/be15fintomatokatchupbe/influencer/query/service/YoutubeService.java
- src/main/resources/application.yml
캠페인 컨텐츠 정보 조회 기능 구현
유튜브 API에서 클릭 수는 가져올 수 없다 하여 댓글 수, 좋아요 수, 조회 수만 일단 가지고 옴.
> TMT 144 be 캠페인 컨텐츠 정보 조회 기능 구현

- src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatSocketController.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageMongoRepository.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/controller/ChatQueryController.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/ChatParticipantDto.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/ChatRoomDetailResponse.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/ChatRoomResponse.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/LastMessageDto.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/MessageResponse.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/UserSimpleDto.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/mapper/ChatRoomQueryMapper.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/service/ChatQueryService.java
- src/main/java/be15fintomatokatchupbe/user/query/mapper/UserQueryMapper.java
- src/main/resources/mappers/chat/chatRoomQueryMapper.xml
- src/main/resources/mappers/user/UserQueryMapper.xml
- src/main/resources/static/test.html
{
"success": true,
"data": {
"chatId": 2,
"messages": [
{
"senderId": 1,
"senderName": "이승재",
"message": "테스트 메시지",
"sentAt": "2025-06-29T18:59:24.468",
"mine": true
},
{
"senderId": 1,
"senderName": "이승재",
"message": "테스트 메시지",
"sentAt": "2025-06-29T19:00:02.263",
"mine": true
},
{
"senderId": 1,
"senderName": "이승재",
"message": "테스트 메시지",
"sentAt": "2025-06-29T19:00:13.681",
"mine": true
},
{
"senderId": 1,
"senderName": "이승재",
"message": "테스트 메시지",
"sentAt": "2025-06-29T19:00:27.73",
"mine": true
},
{
"senderId": 1,
"senderName": "이승재",
"message": "테스트 메시지",
"sentAt": "2025-06-29T19:01:21.4",
"mine": true
},
{
"senderId": 1,
"senderName": "이승재",
"message": "테스트 메시지",
"sentAt": "2025-06-29T19:05:15.238",
"mine": true
},
{
"senderId": 1,
"senderName": "이승재",
"message": "하이하이",
"sentAt": …
> Tmt 159 be 채팅방 목록 조회

- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/CampaignDashboardQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignGetRevenueDTO.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignGetRevenueResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/CampaignDashboardQueryMapper.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
- src/main/resources/mappers/dashboard/CampaignDashboardQueryMapper.xml
> Feat: 캠페인 수익 요약 조회 구현

- src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/UpdateContractRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/ContractCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/QuotationCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/support/CampaignHelperService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
- src/main/java/be15fintomatokatchupbe/file/repository/FileRepository.java
- src/main/java/be15fintomatokatchupbe/file/service/FileService.java
---
- S3에 저장된 파일은 지우지 않음 => 파일 테이블만 hard-delete 해서 연결을 끊는 방식 사용
> 계약 수정 기능 개발

- src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/IdeaCommandController.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/IdeaRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/exception/CampaignErrorCode.java
파이프라인(제안, 견적, 계약, 매출) 의견 등록 기능 구현
> TMT 167 be 파이프라인 의견 등록 기능 구현

- src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Instagram.java
- src/main/java/be15fintomatokatchupbe/oauth/exception/OAuthErrorCode.java
- src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/request/InstagramPermalinkRequest.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/InstagramPostInsightResponse.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramRedisService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramStatsQueryService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramTokenService.java
- src/main/java/be15fintomatokatchupbe/relation/repository/PipeInfClientManagerRepository.java
> Tmt 165 fe 인스타그램 게시물 통계 조회 기능

- src/main/resources/static/test.html
> Refactor/채팅 수정

- src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/ContractCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/ProposalCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/QuotationCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
- src/main/java/be15fintomatokatchupbe/campaign/exception/CampaignErrorCode.java
---
- 제안 삭제
- 견적 삭제
- 계약 삭제
- 매출 삭제
> feat: 파이프라인 삭제 기능 구현

- src/main/java/be15fintomatokatchupbe/notification/command/application/controller/NotificationCommandController.java
- src/main/java/be15fintomatokatchupbe/notification/command/application/service/NotificationCommandService.java
- src/main/java/be15fintomatokatchupbe/notification/command/domain/aggregate/Notification.java
- src/main/java/be15fintomatokatchupbe/notification/exception/NotificationErrorCode.java
> TMT 182 be 알림 읽음 처리 기능 구현

- src/main/java/be15fintomatokatchupbe/notification/command/application/controller/NotificationCommandController.java
- src/main/java/be15fintomatokatchupbe/notification/command/application/service/NotificationCommandService.java
- src/main/java/be15fintomatokatchupbe/notification/command/domain/repository/NotificationRepository.java
> TMT 184 be 알림 전체 삭제 기능 구현

- build.gradle
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/SearchRatioQueryService.java
- src/main/java/be15fintomatokatchupbe/influencer/query/controller/YoutubeController.java
- src/main/java/be15fintomatokatchupbe/influencer/query/service/YoutubeService.java
- src/main/java/be15fintomatokatchupbe/oauth/exception/OAuthErrorCode.java
- src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeQueryController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
> feat/ 유튜브 댓글 가져오기

- src/main/java/be15fintomatokatchupbe/notification/query/controller/NotificationQueryController.java
- src/main/java/be15fintomatokatchupbe/notification/query/dto/NotificationsAllDTO.java
- src/main/java/be15fintomatokatchupbe/notification/query/dto/response/NotificationsAllResponse.java
- src/main/java/be15fintomatokatchupbe/notification/query/mapper/NotificationQueryMapper.java
- src/main/java/be15fintomatokatchupbe/notification/query/service/NotificationQueryService.java
- src/main/resources/mappers/notification/NotificationQueryMapper.xml
> TMT 181 be 알림 전체 조회 기능 구현

- src/main/java/be15fintomatokatchupbe/notification/query/service/NotificationQueryService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/CommentInfo.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/InstagramPostInsightResponse.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
포스트맨 
유튜브/인스타그램 대시보드 → 캠페인 게시글 정보 조회
에서 결과 조회 가능함
> Tmt 190 be 인스타 댓글 갖고오기

- src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/InstagramRepository.java
- src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/scheduler/InstagramInsightScheduler.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramAccountQueryService.java
원래는 인스타계정 id로 조회하게 돼있었는데 (잘못됨) 
인플루언서 id로 조회하게 수정했삼요 (맞음)
> Tmt 193 be 인스타그램 통계 조회 로직 수정

- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignListResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/PipelineStepDto.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/PipelineStepStatusDto.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/PipelineStepMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
- src/main/resources/mappers/campaign/PipelineStepMapper.xml
{
"success": true,
"data": [
{
"campaignId": 1,
"campaignName": "겨울 시즌 캠페인",
"campaignStatusId": 1,
"campaignStatusName": "취소",
"clientCompanyName": "CJ제일제당",
"clientManagerName": "노상철",
"clientManagerPosition": "이사",
"expectedRevenue": 5000000,
"productName": "핫 바디로션",
"startedAt": "2025-07-01",
"endedAt": "2025-08-31",
"pipelineUserName": "장영희",
"pipelineUserPosition": "과장",
"successProbability": 83,
"pipelineSteps": [
{
"stepType": "기획인지",
"startedAt": "2025-07-01"
},
{
"stepType": "제안",
"startedAt": "2025-06-22"
},
{
"stepType": "견적",
"startedAt": "2025-06-25"
},
{
"stepType": "계약",
"startedAt": "2025-06-25"
},
{
"stepType": "매출",
"startedAt": "2025-06-25"
},
{
"stepType": "리스트업",
"startedAt": null
},
{
"stepType": "리스트업",
"startedAt": null
}
]
},
{
"campaignId": 2,
"campaignName": …
> Tmt 156 be 캠페인 목록 조회 기능 구현

- src/main/java/be15fintomatokatchupbe/file/service/FileService.java
- src/main/java/be15fintomatokatchupbe/user/command/application/controller/UserCommandController.java
- src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
- src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/User.java
- src/test/java/be15fintomatokatchupbe/user/command/application/service/UserCommendServiceTest.java
> Fix: 이미지 조회기능 수정

- src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
> Tmt 201 be 인스타그램 댓글 요약

- src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/CampaignSimpleDto.java
- src/main/java/be15fintomatokatchupbe/client/query/controller/ClientManagerQueryController.java
- src/main/java/be15fintomatokatchupbe/influencer/query/controller/InfluencerQueryController.java
- src/main/java/be15fintomatokatchupbe/influencer/query/dto/response/InfluencerSearchDto.java
- src/main/java/be15fintomatokatchupbe/influencer/query/dto/response/InfluencerSearchResponse.java
- src/main/java/be15fintomatokatchupbe/influencer/query/mapper/InfluencerMapper.java
- src/main/java/be15fintomatokatchupbe/influencer/query/service/InfluencerQueryService.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserListResponse.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserSearchDto.java
- src/main/java/be15fintomatokatchupbe/user/query/mapper/UserQueryMapper.java
- src/main/java/be15fintomatokatchupbe/user/query/service/UserQueryService.java
- src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
- src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
- src/main/resources/mappers/client/ClientManagerQueryMapper.xml
- src/main/resources/mappers/user/UserQueryMapper.xml
> refactor: 팝업 로직 수정

- src/main/java/be15fintomatokatchupbe/user/query/controller/UserQueryController.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserAccountQueryResponse.java
- src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserHeaderAccountResponse.java
- src/main/java/be15fintomatokatchupbe/user/query/mapper/UserQueryMapper.java
- src/main/java/be15fintomatokatchupbe/user/query/service/UserQueryService.java
- src/main/resources/mappers/user/UserQueryMapper.xml
> Feat: 헤더에서 내 기본정보 조회 기능 구현

- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/SearchRatioQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/SearchRatioQueryMapper.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/SearchRatioQueryService.java
- src/main/java/be15fintomatokatchupbe/influencer/query/controller/YoutubeController.java
1. campaignId -> pipelineInfluencerId로 refactor
> Tmt 207 be 전체 수정

- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandService.java
- src/main/java/be15fintomatokatchupbe/user/command/application/repository/UserRepository.java
- src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
- src/main/java/be15fintomatokatchupbe/user/exception/UserErrorCode.java
- src/main/java/be15fintomatokatchupbe/user/query/controller/UserQueryController.java
> Fix: 비밀번호 변경 수정

- src/main/java/be15fintomatokatchupbe/config/JwtHandshakeInterceptor.java
- src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
- src/main/java/be15fintomatokatchupbe/config/StompAuthChannelInterceptor.java
- src/main/java/be15fintomatokatchupbe/config/WebSocketConfig.java
> Tmt 211 be 채팅 전송 수정

- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandService.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatSocketController.java
- src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
- src/main/java/be15fintomatokatchupbe/email/command/domain/aggregate/Satisfaction.java
- src/main/java/be15fintomatokatchupbe/email/query/dto/response/CampaignSatisfactionDTO.java
- src/main/java/be15fintomatokatchupbe/email/query/service/EmailQueryService.java
- src/main/java/be15fintomatokatchupbe/notification/command/application/dto/response/NotificationPipeLineResponse.java
- src/main/java/be15fintomatokatchupbe/notification/command/application/service/NotificationSchedulerService.java
- src/main/java/be15fintomatokatchupbe/notification/command/domain/aggregate/Notification.java
- src/main/java/be15fintomatokatchupbe/notification/query/dto/NotificationsAllDTO.java
- src/main/resources/mappers/calendar/TodayScheduleCommandMapper.xml
- src/main/resources/mappers/email/EmailQueryMapper.xml
> Fix: 이메일시스템쪽 코드 수정

- src/main/java/be15fintomatokatchupbe/influencer/query/controller/InfluencerQueryController.java
- src/main/java/be15fintomatokatchupbe/influencer/query/mapper/InfluencerMapper.java
- src/main/java/be15fintomatokatchupbe/influencer/query/service/InfluencerQueryService.java
- src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
> Tmt 216 be 카테고리 목록 조회 기능 구현

- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageMongoRepository.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageMongoRepositoryCustom.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageMongoRepositoryImpl.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/ChatRoomDetailResponse.java
- src/main/java/be15fintomatokatchupbe/chat/query/application/service/ChatQueryService.java
> feat: 읽지 않은 채팅 수 구현

- src/main/java/be15fintomatokatchupbe/influencer/query/dto/response/InfluencerCardResponse.java
- src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
> Tmt 220 be 인플루언서 조회 쿼리 수정

- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/MainDashboardQueryController.java
> Tmt 224 be 메인 대시보드 조회 기능 로직 수정

- src/main/java/be15fintomatokatchupbe/contract/command/application/controller/ContractCommandController.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/ObjectCreateRequest.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/ContractObjectCommandService.java
- src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
- src/main/java/be15fintomatokatchupbe/utils/FileUtil.java
> Tmt 222 be 템플릿 저장 수정

- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ContractResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ProposalResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/QuotationResponse.java
- src/main/resources/mappers/dashboard/MainDashboardQueryMapper.xml
> Tmt 235 be 메인 대시보드 조회 쿼리 수정

- src/main/java/be15fintomatokatchupbe/influencer/query/service/InfluencerQueryService.java
- src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
> Tmt 236 be 인플루언서 페이징 수정

- src/main/java/be15fintomatokatchupbe/influencer/command/application/dto/request/InfluencerRegisterRequestDTO.java
- src/main/java/be15fintomatokatchupbe/influencer/command/application/service/InfluencerCommandServiceImpl.java
> refactor: 인플루언서 등록 엔드포인트 분리

- src/main/java/be15fintomatokatchupbe/influencer/query/dto/response/InstagramInfoResponse.java
- src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
> Tmt 239 be 인스타그램 정보 조회 쿼리 수정

- src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeQueryController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeStatsSnapshot.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeVideoInfo.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/YoutubeStatsResponse.java
- src/main/java/be15fintomatokatchupbe/oauth/query/mapper/YoutubeQueryMapper.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeSnapshotQueryService.java
- src/main/resources/mappers/oauth/youtubeQueryMapper.xml
> Tmt 247 be 유튜브 스냅샷 테이블 조회 기능 추가

- src/main/java/be15fintomatokatchupbe/contract/command/application/controller/ContractCommandController.java
- src/main/java/be15fintomatokatchupbe/utils/EmailUtils.java
파일 리스트 형태로 변경해서 여러 개 보내기 구현 완료
> refactor: 메일로 파일 여러개 보내기

- .gitignore
> chore: 테라폼 gitignore 추가

- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/ListupCardDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/ListupFormDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ListupCardResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ListupDetailResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ListupSearchResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> 리스트업 목록 조회

- src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/CampaignResultRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> feat: 캠페인 성과 조회 구현 수정

- src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeStatsSnapshot.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeSnapshotQueryService.java
- src/main/resources/mappers/oauth/youtubeQueryMapper.xml
> Tmt 256 be 유튜브 계정 통계 연령대 응답 구조 수정

- src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/constant/CampaignStatusConstants.java
- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/CampaignWithCategoryDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignAiResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> fix: 리스트업 캠페인 검색 개발

- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignResponse.java
- src/main/resources/mappers/dashboard/PlatformDashboardQueryMapper.xml
> Tmt 267 be 인플루언서별 진행 캠페인 조회 쿼리 수정

- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignListDTO.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignListResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> 캠페인 페이지네이션 수정

- src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/CampaignResultRequest.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignInfluencerInfo.java
- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignResultResponse.java
- src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
- src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> Tmt 269 성과목록 조회

- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignResponse.java
- src/main/resources/mappers/dashboard/PlatformDashboardQueryMapper.xml
> Tmt 270 be 성과 대시보드 이동 위해 picm id 조회 추가

- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/CampaignDashboardQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/CampaignDashboardQueryMapper.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
캠페인 컨텐츠 정보 조회 수정 => 엔드포인트 수정
https://www.youtube.com/watch?v=KXH-Q4m3jTQ
> Tmt 281 be 캠페인 컨텐츠 정보 조회 수정

- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
ROW_NUMBER()로 파이프라인마다 하나의 client_manager만 가져옴
> fix: 캠페인 고객사 커뮤니케이션 스텝 중복 이슈 수정

- src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramSchedulerTestController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/domain/InstagramMediaSnapshot.java
- src/main/java/be15fintomatokatchupbe/oauth/query/domain/InstagramStatsSnapshot.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/InstagramFullSnapshot.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/InstagramMediaStats.java
- src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/InstagramStatsResponse.java
- src/main/java/be15fintomatokatchupbe/oauth/query/scheduler/InstagramInsightScheduler.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramAccountQueryService.java
- src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramStatsSnapshotService.java
- src/main/resources/mappers/oauth/instagramQueryMapper.xml
> Tmt 287 be 인스타 유튜브 api 응답 수정

- src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
인플루언서 분석 필터링 수정(검색 입력란에 인스타그램, 유튜브 추가 포함)
> TMT 293 be 인플루언서 분석 필터링 수정

- src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyContractDto.java
- src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
> Tmt 297 be 파이프라인 인플루언서 아이디 필드 추가

- src/main/java/be15fintomatokatchupbe/oauth/command/application/controller/YoutubeCommandController.java
- src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramSchedulerTestController.java
- src/main/java/be15fintomatokatchupbe/oauth/scheduler/InstagramInsightScheduler.java
- src/main/java/be15fintomatokatchupbe/oauth/scheduler/YoutubeStatsSnapshotScheduler.java
> Refactor: scheduler package 이동

- src/main/resources/application.yml
> feat: time-out 시간 수정

- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> fix: 캠페인 목록 조회 쿼리 담당자 매핑 수정

- src/main/java/be15fintomatokatchupbe/calendar/query/dto/pipeline/PipelineScheduleListDTO.java
- src/main/resources/mappers/calendar/PipelineScheduleQueryMapper.xml
캘린더 파이프라인 일정 가져오기 수정 - campaign_id, pipeline_step_id 추가
> fix - 캘린더 파이프라인 일정 가져오기 수정

- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandService.java
- src/main/java/be15fintomatokatchupbe/dashboard/command/application/support/DashboardHelperService.java
- src/main/java/be15fintomatokatchupbe/dashboard/command/domain/aggregate/InfluencerTraffic.java
- src/main/java/be15fintomatokatchupbe/dashboard/command/domain/aggregate/Traffic.java
- src/main/java/be15fintomatokatchupbe/dashboard/command/domain/repository/InfluencerTrafficRepository.java
- src/main/java/be15fintomatokatchupbe/dashboard/command/domain/repository/TrafficRepository.java
- src/main/java/be15fintomatokatchupbe/file/service/FileService.java
- src/main/java/be15fintomatokatchupbe/relation/domain/PipelineInfluencerClientManager.java
- src/main/java/be15fintomatokatchupbe/relation/repository/PipeInfClientManagerRepository.java
- src/main/java/be15fintomatokatchupbe/relation/service/PipeInfClientManagerService.java
> feat: 트래픽 더미 자동 생성

- src/main/java/be15fintomatokatchupbe/email/query/controller/EmailQueryController.java
- src/main/java/be15fintomatokatchupbe/email/query/dto/response/InfluencerSatisfactionResponse.java
- src/main/java/be15fintomatokatchupbe/email/query/mapper/EmailQueryMapper.java
- src/main/java/be15fintomatokatchupbe/email/query/service/EmailQueryService.java
- src/main/resources/mappers/email/EmailQueryMapper.xml
대시보드 페이지에서 처리하려고 만족도 조사 개수도 같이 조회되게 함
> Tmt 319 be 인플루언서 만족도 조회 쿼리 수정

- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/CampaignDashboardQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/controller/TrafficQueryController.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignGetRevenueDTO.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ThumbnailResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/TrafficResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/TrafficQueryMapper.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/TrafficQueryService.java
- src/main/resources/mappers/dashboard/CampaignDashboardQueryMapper.xml
- src/main/resources/mappers/dashboard/TrafficQueryMapper.xml
1. 유입분석
2. 수익률
3. ai 댓글 요약
4. 주간 데이터 조회
> refactor: 전체적인 수정

- src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
- src/main/java/be15fintomatokatchupbe/contract/exception/ContractErrorCode.java
- src/main/java/be15fintomatokatchupbe/file/service/FileService.java
- src/main/java/be15fintomatokatchupbe/utils/FileUtil.java
> refactor: 템플릿 수정

- src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/PipelineStepsDto.java
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
- src/main/resources/mappers/contract/ContractSuccessQueryMapper.xml
> Fix: 선택된 단계까지만 뜨게 변경

- build.gradle
- src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
- src/main/resources/application.yml
> chore:헬스체크 추가

- src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatSocketController.java
- src/main/java/be15fintomatokatchupbe/chat/command/application/service/ChatCommandService.java
- src/main/java/be15fintomatokatchupbe/chat/command/domain/aggregate/entity/Message.java
> refactor : 채팅 수정

- src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignContentResponse.java
- src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
- src/main/java/be15fintomatokatchupbe/influencer/query/service/InfluencerQueryService.java
- src/main/java/be15fintomatokatchupbe/influencer/query/service/YoutubeService.java
> refactor : DTO에 썸네일 추가

- main.tf
- src/main/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandService.java
- src/main/resources/application-dev.yml
- src/main/resources/mappers/campaign/CampaignQueryMapper.xml
> fix:캠페인 삭제 수정
